# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elo_test.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(150, 70, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(120, 70, 16, 17))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 110, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(120, 110, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(120, 150, 16, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 150, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(120, 190, 16, 17))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 190, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(120, 230, 16, 17))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 230, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(120, 270, 16, 17))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 270, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 360, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.mu_1 = QtWidgets.QLabel(self.centralwidget)
        self.mu_1.setGeometry(QtCore.QRect(250, 80, 47, 13))
        self.mu_1.setObjectName("mu_1")
        self.mu_2 = QtWidgets.QLabel(self.centralwidget)
        self.mu_2.setGeometry(QtCore.QRect(250, 120, 47, 13))
        self.mu_2.setObjectName("mu_2")
        self.mu_3 = QtWidgets.QLabel(self.centralwidget)
        self.mu_3.setGeometry(QtCore.QRect(250, 160, 47, 13))
        self.mu_3.setObjectName("mu_3")
        self.mu_4 = QtWidgets.QLabel(self.centralwidget)
        self.mu_4.setGeometry(QtCore.QRect(250, 200, 47, 13))
        self.mu_4.setObjectName("mu_4")
        self.mu_5 = QtWidgets.QLabel(self.centralwidget)
        self.mu_5.setGeometry(QtCore.QRect(250, 240, 47, 13))
        self.mu_5.setObjectName("mu_5")
        self.mu_6 = QtWidgets.QLabel(self.centralwidget)
        self.mu_6.setGeometry(QtCore.QRect(250, 280, 47, 13))
        self.mu_6.setObjectName("mu_6")
        self.sig_1 = QtWidgets.QLabel(self.centralwidget)
        self.sig_1.setGeometry(QtCore.QRect(330, 80, 47, 13))
        self.sig_1.setObjectName("sig_1")
        self.sig_2 = QtWidgets.QLabel(self.centralwidget)
        self.sig_2.setGeometry(QtCore.QRect(330, 120, 47, 13))
        self.sig_2.setObjectName("sig_2")
        self.sig_3 = QtWidgets.QLabel(self.centralwidget)
        self.sig_3.setGeometry(QtCore.QRect(330, 160, 47, 13))
        self.sig_3.setObjectName("sig_3")
        self.sig_4 = QtWidgets.QLabel(self.centralwidget)
        self.sig_4.setGeometry(QtCore.QRect(330, 200, 47, 13))
        self.sig_4.setObjectName("sig_4")
        self.sig_5 = QtWidgets.QLabel(self.centralwidget)
        self.sig_5.setGeometry(QtCore.QRect(330, 240, 47, 13))
        self.sig_5.setObjectName("sig_5")
        self.sig_6 = QtWidgets.QLabel(self.centralwidget)
        self.sig_6.setGeometry(QtCore.QRect(330, 280, 47, 13))
        self.sig_6.setObjectName("sig_6")
        self.sig_7 = QtWidgets.QLabel(self.centralwidget)
        self.sig_7.setGeometry(QtCore.QRect(340, 30, 47, 13))
        self.sig_7.setObjectName("sig_7")
        self.mu_7 = QtWidgets.QLabel(self.centralwidget)
        self.mu_7.setGeometry(QtCore.QRect(260, 30, 31, 16))
        self.mu_7.setObjectName("mu_7")
        self.mu_8 = QtWidgets.QLabel(self.centralwidget)
        self.mu_8.setGeometry(QtCore.QRect(290, 10, 47, 13))
        self.mu_8.setObjectName("mu_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "Player 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Player 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Player 3"))
        self.pushButton_4.setText(_translate("MainWindow", "Player 4"))
        self.pushButton_5.setText(_translate("MainWindow", "Player 5"))
        self.pushButton_6.setText(_translate("MainWindow", "Player 6"))
        self.pushButton_7.setText(_translate("MainWindow", "Reset"))
        self.mu_1.setText(_translate("MainWindow", "TextLabel"))
        self.mu_2.setText(_translate("MainWindow", "TextLabel"))
        self.mu_3.setText(_translate("MainWindow", "TextLabel"))
        self.mu_4.setText(_translate("MainWindow", "TextLabel"))
        self.mu_5.setText(_translate("MainWindow", "TextLabel"))
        self.mu_6.setText(_translate("MainWindow", "TextLabel"))
        self.sig_1.setText(_translate("MainWindow", "TextLabel"))
        self.sig_2.setText(_translate("MainWindow", "TextLabel"))
        self.sig_3.setText(_translate("MainWindow", "TextLabel"))
        self.sig_4.setText(_translate("MainWindow", "TextLabel"))
        self.sig_5.setText(_translate("MainWindow", "TextLabel"))
        self.sig_6.setText(_translate("MainWindow", "TextLabel"))
        self.sig_7.setText(_translate("MainWindow", "sigma"))
        self.mu_7.setText(_translate("MainWindow", "mu"))
        self.mu_8.setText(_translate("MainWindow", "ELO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

